<?php

namespace Database\Seeders;

use App\Models\Package;
use Illuminate\Database\Seeder;

class CreatePackage extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $packages = [
            [
                "name"    => "instagram",
                "label"   => "Follower",
                "type"    => "follower",
                "price"   => 25000,
                "benefits" => 50,
            ],
            [
                "name"    => "instagram",
                "label"   => "Follower",
                "type"    => "follower",
                "price"   => 50000,
                "benefits" => 100,
            ],
            [
                "name"    => "instagram",
                "label"   => "Follower",
                "type"    => "follower",
                "price"   => 100000,
                "benefits" => 200,
            ],
            [
                "name"    => "instagram",
                "label"   => "Follower",
                "type"    => "follower",
                "price"   => 150000,
                "benefits" => 300,
            ],
            [
                "name"    => "instagram",
                "label"   => "Follower",
                "type"    => "follower",
                "price"   => 200000,
                "benefits" => 400,
            ],
            [
                "name"    => "instagram",
                "label"   => "Follower",
                "type"    => "follower",
                "price"   => 250000,
                "benefits" => 500,
            ],
            [
                "name"    => "instagram",
                "label"   => "Follower",
                "type"    => "follower",
                "price"   => 450000,
                "benefits" => 1000,
            ],
            [
                "name"    => "instagram",
                "label"   => "Follower",
                "type"    => "follower",
                "price"   => 1750000,
                "benefits" => 5000,
            ],
            [
                "name"    => "instagram",
                "label"   => "Follower",
                "type"    => "follower",
                "price"   => 3500000,
                "benefits" => 10000,
            ],
            [
                "name"    => "instagram",
                "label"   => "Follower",
                "type"    => "follower",
                "price"   => 17500000,
                "benefits" => 50000,
            ],
            [
                "name"    => "instagram",
                "label"   => "Follower",
                "type"    => "follower",
                "price"   => 35000000,
                "benefits" => 100000,
            ],


            [
                "name"    => "comment",
                "label"   => "Komentar",
                "type"    => "comment",
                "price"   => 7500,
                "benefits" => 10,
            ],
            [
                "name"    => "comment",
                "label"   => "Komentar",
                "type"    => "comment",
                "price"   => 15000,
                "benefits" => 20,
            ],
            [
                "name"    => "comment",
                "label"   => "Komentar",
                "type"    => "comment",
                "price"   => 22500,
                "benefits" => 30,
            ],
            [
                "name"    => "comment",
                "label"   => "Komentar",
                "type"    => "comment",
                "price"   => 30000,
                "benefits" => 40,
            ],
            [
                "name"    => "comment",
                "label"   => "Komentar",
                "type"    => "comment",
                "price"   => 37500,
                "benefits" => 50,
            ],
            [
                "name"    => "comment",
                "label"   => "Komentar",
                "type"    => "comment",
                "price"   => 70000,
                "benefits" => 100,
            ],
            [
                "name"    => "comment",
                "label"   => "Komentar",
                "type"    => "comment",
                "price"   => 350000,
                "benefits" => 500,
            ],
            [
                "name"    => "comment",
                "label"   => "Komentar",
                "type"    => "comment",
                "price"   => 700000,
                "benefits" => 1000,
            ],
            [
                "name"    => "comment",
                "label"   => "Komentar",
                "type"    => "comment",
                "price"   => 3500000,
                "benefits" => 5000,
            ],
            [
                "name"    => "comment",
                "label"   => "Komentar",
                "type"    => "comment",
                "price"   => 7000000,
                "benefits" => 10000,
            ],

            [
                "name"    => "posting",
                "label"   => "Posting",
                "type"    => "posting",
                "price"   => 15000,
                "benefits" => 100,
            ],
            [
                "name"    => "posting",
                "label"   => "Posting",
                "type"    => "posting",
                "price"   => 37500,
                "benefits" => 250,
            ],
            [
                "name"    => "posting",
                "label"   => "Posting",
                "type"    => "posting",
                "price"   => 75000,
                "benefits" => 500,
            ],
            [
                "name"    => "posting",
                "label"   => "Posting",
                "type"    => "posting",
                "price"   => 150000,
                "benefits" => 1000,
            ],
            [
                "name"    => "posting",
                "label"   => "Posting",
                "type"    => "posting",
                "price"   => 750000,
                "benefits" => 5000,
            ],
            [
                "name"    => "posting",
                "label"   => "Posting",
                "type"    => "posting",
                "price"   => 1500000,
                "benefits" => 10000,
            ],
            [
                "name"    => "posting",
                "label"   => "Posting",
                "type"    => "posting",
                "price"   => 7500000,
                "benefits" => 50000,
            ],
            [
                "name"    => "posting",
                "label"   => "Posting",
                "type"    => "posting",
                "price"   => 15000000,
                "benefits" => 100000,
            ],

            [
                "name"    => "like",
                "label"   => "likes",
                "type"    => "like",
                "price"   => 15000,
                "benefits" => 100,
            ],
            [
                "name"    => "like",
                "label"   => "likes",
                "type"    => "like",
                "price"   => 37500,
                "benefits" => 250,
            ],
            [
                "name"    => "like",
                "label"   => "likes",
                "type"    => "like",
                "price"   => 75000,
                "benefits" => 500,
            ],
            [
                "name"    => "like",
                "label"   => "likes",
                "type"    => "like",
                "price"   => 150000,
                "benefits" => 1000,
            ],
            [
                "name"    => "like",
                "label"   => "likes",
                "type"    => "like",
                "price"   => 750000,
                "benefits" => 5000,
            ],
            [
                "name"    => "like",
                "label"   => "likes",
                "type"    => "like",
                "price"   => 1500000,
                "benefits" => 10000,
            ],
            [
                "name"    => "like",
                "label"   => "likes",
                "type"    => "like",
                "price"   => 7500000,
                "benefits" => 50000,
            ],
            [
                "name"    => "like",
                "label"   => "likes",
                "type"    => "like",
                "price"   => 15000000,
                "benefits" => 100000,
            ],

            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 30000,
                "benefits" => 100,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 60000,
                "benefits" => 200,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 90000,
                "benefits" => 300,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 120000,
                "benefits" => 400,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 150000,
                "benefits" => 500,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 180000,
                "benefits" => 600,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 210000,
                "benefits" => 700,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 240000,
                "benefits" => 800,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 270000,
                "benefits" => 900,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 300000,
                "benefits" => 1000,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 600000,
                "benefits" => 2000,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 900000,
                "benefits" => 3000,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 1200000,
                "benefits" => 4000,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 1500000,
                "benefits" => 5000,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 1800000,
                "benefits" => 6000,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 2100000,
                "benefits" => 7000,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 2400000,
                "benefits" => 8000,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 2700000,
                "benefits" => 9000,
            ],
            [
                "name"    => "subscribe",
                "label"   => "Subscribe",
                "type"    => "subscribe",
                "price"   => 3000000,
                "benefits" => 10000,
            ],

            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 5,
                "benefits" => 5,
                "commission" => 4,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 10,
                "benefits" => 10,
                "commission" => 7,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 15,
                "benefits" => 15,
                "commission" => 12,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 20,
                "benefits" => 20,
                "commission" => 15,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 25,
                "benefits" => 25,
                "commission" => 20,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 30,
                "benefits" => 30,
                "commission" => 25,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 50,
                "benefits" => 60,
                "commission" => 30,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 60,
                "benefits" => 120,
                "commission" => 40,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 90,
                "benefits" => 180,
                "commission" => 60,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 120,
                "benefits" => 240,
                "commission" => 110,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 150,
                "benefits" => 300,
                "commission" => 330,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 300,
                "benefits" => 600,
                "commission" => 150,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 450,
                "benefits" => 900,
                "commission" => 250,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 600,
                "benefits" => 1200,
                "commission" => 350,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 750,
                "benefits" => 1500,
                "commission" => 450,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 900,
                "benefits" => 1800,
                "commission" => 550,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 1200,
                "benefits" => 2400,
                "commission" => 650,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 1500,
                "benefits" => 3000,
                "commission" => 750,
            ],
            [
                "name"    => "views",
                "label"   => "Detik",
                "type"    => "views",
                "price"   => 1800,
                "benefits" => 3600,
                "commission" => 850,
            ],
        ];

        foreach ($packages as $package):
            Package::updateOrCreate([
                'name' => $package['name'],
                'label' => $package['label'],
                'type' => $package['type'],
                'price' => $package['price'],
                'benefits' => $package['benefits'],
                'commission' => $package['commission'] ?? 0,
            ]);
        endforeach;
    }
}
